### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by UrKr** [jdeal/qim#11]
Very nice! Specter in clojure is very impressive, glad you took the effort of implementing something similar in javascript.

Do you have any opinions on how this would be typed for Typescript. Do you think it's viable?

**Comment by jdeal** [comment]
Thanks!

It's at least _partially_ viable in terms of at least making sure that methods and navigators are properly typed. But there are likely to be significant limits. `qim`'s dynamic flexibility is somewhat of a mismatch for static typing. It's kind of a tradeoff. If you want strong type safety, you have to write a lot of discrete typed helper functions. If you want flexible, terse usage like `qim`, it's kind of hard for a type system to make that safe.

At some point, I'd really like to try though!

On a related note, I'll probably be using Flow when I take a stab. But there's no reason TS type definitions couldn't be provided too.
