### ISSUE TITLE
Iterables (and possible breaking change for `$each` and other navigators)

### ISSUE THREAD

**Issue by jdeal** [jdeal/qim#4]
I'd like to add support for [iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols). This would automatically add support for `Map`, Immutable.js, etc.

One immediately obvious problem is the semantics of `$each`. Currently, `$each` iterates over each value of an array or object. This mirrored Lodash's `_.each` semantics. If you want to iterate over each pair, you use `$eachPair`.

Iterating over an iterable though is meant to iterate over each of its "entries". So in the case of `Map`, that's each key/value pair. In the case of an array, that's each value. There's also a stage 4 proposal for `Object.entries` which behaves the same way as `Map.prototype.entries`.

This probably means that `$each` should probably change to be values for an array and pairs for an object. But that means this:

```js
select([$each], {x: 1, y: 2})
// [1, 2]
```

Would have to become this:

```js
select([$each, 1], {x: 1, y: 2})
// [1, 2]
```

Which is kind of ugly. And it prevents you from being able to use the same query on an array or an object, which is often useful. To mitigate that, the current `$each` behavior could probably move to `$eachValue` (which is what it was originally named). If an object has a `.values` function, that can be used as the iterable for `$eachValue`. So you could have:

```js
select([$eachValue], {x: 1, y: 2})
// [1, 2]
```

Another option would be to leave `$each` as-is and add an `$eachEntry` navigator, but that feels like it's just adding more API surface area.

A less significant question is whether or not to keep `$eachPair` after this change. It has arguably limited usefulness for arrays, and for objects, it would effectively be a duplicate of `$each`. There's no `pairs` method for iterables, but looking for `keys` function _should_ be enough of a clue to determine if `entries` returns pairs. There's no rule that says an iterable has to implement these though, or that they have to keep the naming convention, so it's kind of ambiguous how it should behave in those cases. Throw an error? `qim` could offer a custom protocol for filling in these gaps (like transducers).

There's also the question of `$first` and `$last`. Currently, they return the first and last _value_. So after this change, should they return the first and last _entry_ instead? Should there be an equivalent `$firstValue` and `$lastValue` to grab the first and last value? The first and last value of an object has less meaning than for arrays, so I think the semantics change here is of less impact, and `$firstValue` and `$lastValue` can wait until there's a real need.

I'll have to dig into code more to figure out how iterables will affect creating custom navigators, i.e. `$traverse`. I wanted to surface this change right away though.

**Comment by jdeal** [comment]
Hmm,  on second thought...

`Map.prototype.forEach` gets the value as the first parameter and the key as the second parameter, more like Lodash's `_.each`, so maybe the current semantics are reasonable. Likewise, Immutable.js `.forEach` has the same behavior.

But with `qim`, there's no way to get that second parameter. That's what had me thinking about `.entries().forEach` instead.

But maybe `$eachValue` would be more explicit and remove any ambiguity. Likewise, `$eachEntry` might be more explicit if type-dependent iteration is desirable.

The crucial questions are:

1. Is it obvious (enough) that `$each` operates on values?
2. Is it ever desirable to navigate to an entry? Meaning, navigate to a value _or_ a pair, depending on the type of thing we're navigating to.
3. What about `$first` and `$last` that currently navigate to the first and last value? Should they work with entries instead? Or should there be `$firstEntry` and `$lastEntry`?
4. What about things like `$slice` that currently only work on arrays. Should that work with entries? Should it work with values of an object/Map?

Navigating to each value, regardless of type, seems to be the common case, so that's why `$each` currently navigates to each value. I'd rather not add a bunch of suffixes to different navigators, but there is some ambiguity there now, especially when iterables are added.

**Comment by jdeal** [comment]
@bryanhelmig @stevenhauser @neilff Dragging you into this discussion (re iterables and `$each`) in case you have opinions. Otherwise, I'll eventually type enough comments to make up my own mind. :-) So feel free to ignore.

**Comment by jdeal** [comment]
Another possibility is having navigators return iterables that are lazy sequences. Then I could introduce `$values`, `$keys`, `$pairs`, and `$entries`. Then I'd take out everything except `$each`, since you could just precede it with any iterable-returning navigator. For example `$pairs, $each` instead of `$eachPair`. If you really wanted an `$eachPair`, you could just create it like:

```js
const $eachPair = $nav([$pairs, $each]);
```

If you want uniform behavior of arrays and objects:
```js
const $eachValue = $nav([$values, $each]);
```

That also eliminates any need to disambiguate other navigators like `$first`, `$slice`, etc. They would just work on iterables, so if you want the first value, just use `$values, $first`. If you want to slice entries, then do `$entries, $slice(0,5)`, etc., etc. This would fill in some currently missing behavior where you can't, for example, slice off the first 5 pairs of an object. (So independent of the iterable decision, `$values`, `$keys`, and `$pairs` probably should be added.)

Some questions then:

1. How would this affect performance? There could be a lot of wrapping/unwrapping between navigators.
2. How would it affect internal implementation complexity? `traverse` would certainly become more complex. Some kind of internal sequence class would have to be created to abstract away sequence behavior for arrays, objects, and iterables.
3. How would it affect custom navigator implementation complexity? Custom navigators would have to deal with abstract sequence objects instead of raw arrays and objects.

No way to know the answers here unless I try to implement something.

One could imagine extending this to support async iterables, but that would likely increase complexity even more and drag down synchronous performance even more.

**Comment by stevenhauser** [comment]
Whew, lots of questions to be answered @jdeal. I mostly follow them but since I haven't used `qim` at all it's difficult to see everything really clearly. 

Starting from an API perspective, can you give concrete examples of each idea you have using the same data structures for every example and briefly explain pros and cons of each one? I think that could help clarify what the options are and by doing a comparison like that potentially reveal the pros and 🌽s of each approach much more clearly, or even reveal a new approach.

**Comment by jdeal** [comment]
@stevenhauser

Hopefully this is what you wanted. This isn't an exhaustive list of everything that would change with all the options, but hopefully it's enough to illustrate the main points.

**Current behavior**

```js
select([$each, 'name'], [{name: 'Joe'}, {name: 'Mary'}])
// ['Joe', 'Mary']
```

```js
select([$each, 'name'], {joe123: {name: 'Joe'}, mary123: {name: 'Mary'}})
// ['Joe', 'Mary']
```

```js
// Not supported.
select([$each, 'name'], new Map([['joe123', {name: 'Joe'}], ['mary123', {name: 'Mary'}]]))
// []
```

**Option 1: Add iterable support, and have `$each` use `.forEach()` or `.values()` so that it always iterates over values.**

Basically, the idea is to keep the current semantics intact but add in support for iterables.

```js
select([$each, 'name'], [{name: 'Joe'}, {name: 'Mary'}])
// ['Joe', 'Mary']
```

```js
select([$each, 'name'], {joe123: {name: 'Joe'}, mary123: {name: 'Mary'}})
// ['Joe', 'Mary']
```

```js
select([$each, 'name'], new Map([['joe123', {name: 'Joe'}], ['mary123', {name: 'Mary'}]]))
// ['Joe', 'Mary']
```

Note that `.forEach` and `.values` are not part of the iterable protocol, so there's no guarantee it would work across _all_ iterables. We could fallback to `Symbol.iterator` when there's no `.forEach`, but there's also the risk that `forEach` exists but doesn't behave as expected.

**Option 2: Have `$each` work with the iterable protocol and simply iterate over whatever the `Symbol.iterator` returns.**

The idea here is to add in iterables but make the semantics more explicit.

```js
select([$each, 'name'], [{name: 'Joe'}, {name: 'Mary'}])
// ['Joe', 'Mary']
```

```js
// There's no `Symbol.iterator` on `Object`, but we could use `Object.entries`.
select([$each, 1, 'name'], {joe123: {name: 'Joe'}, mary123: {name: 'Mary'}})
// ['Joe', 'Mary']
```

```js
select([$each, 1, 'name'], new Map([['joe123', {name: 'Joe'}], ['mary123', {name: 'Mary'}]]))
// ['Joe', 'Mary']
```

With this option, we might want to add in `$eachValue` to get back the current behavior.

```js
select([$eachValue, 'name'], [{name: 'Joe'}, {name: 'Mary'}])
// ['Joe', 'Mary']
```

```js
select([$eachValue, 'name'], {joe123: {name: 'Joe'}, mary123: {name: 'Mary'}})
// ['Joe', 'Mary']
```

```js
select([$eachValue, 'name'], new Map([['joe123', {name: 'Joe'}], ['mary123', {name: 'Mary'}]]))
// ['Joe', 'Mary']
```

**Option 3: Add in `$values` that passes along an iterable and have `$each` just iterate on iterables. Get rid of the other `$each*` navigators.**

The idea is to separate navigators that create iterators from the navigators that do the iteration.

```js
// `$values` would just be a pass-through here, since an array is already iterable
select([$values, $each, 'name'], [{name: 'Joe'}, {name: 'Mary'}])
// ['Joe', 'Mary']
```

```js
select([$values, $each, 'name'], {joe123: {name: 'Joe'}, mary123: {name: 'Mary'}})
// ['Joe', 'Mary']
```

```js
select([$values, $each, 'name'], new Map([['joe123', {name: 'Joe'}], ['mary123', {name: 'Mary'}]]))
// ['Joe', 'Mary']
```

**Comment by bryanhelmig** [comment]
With minimal context, `$each`, to me, grabs values which is 90% of what one would use. Practicality trumps purity. I see no reason to not add `$eachEntry` and allow folks to passed the arity index (?) after. `$eachKey` is sugar on `[$eachEntry, 0]` (maybe just omit this?) and `$each` is sugar on `[$eachEntry, 1]`.

**Comment by jdeal** [comment]
> Practicality trumps purity

That's kind of where I'm landing @bryanhelmig.

> I see no reason to not add $eachEntry

There already is an `$eachPair` navigator, and I think its behavior is what you're describing for `$eachEntry`. When I mentioned `$eachEntry`, I was talking about perhaps adding something that iterated according to `Symbol.iterator` behavior:

```bash
➜  ~ node
> const array = ['a','b']
undefined
> [...array]
[ 'a', 'b' ]
> const map = new Map()
undefined
> map.set(0, 'a')
Map { 0 => 'a' }
> map.set(1, 'b')
Map { 0 => 'a', 1 => 'b' }
> [...map]
[ [ 0, 'a' ], [ 1, 'b' ] ]
```

However, I was surprised (just now) to find out that `Array.prototype.entries` actually returns pairs.

```bash
> [...array.entries()]
[ [ 0, 'a' ], [ 1, 'b' ] ]
> [...map.entries()]
[ [ 0, 'a' ], [ 1, 'b' ] ]
```

So I guess "entry" is just a synonym for "pairs", so scratch a lot of what I said when I opened this issue, since I should have done a bit more digging first! I think the current behavior of `$each`, `$eachPair` and `$eachKey` is pretty reasonable, so I'm going to leave that as-is. Point taken that `$eachKey` is unnecessary sugar, but it's a tad more performant than `$eachPair, 0`, so I'm going to leave it for now too.

I still think there's some ambiguity around `$first`, `$slice`, etc. that should be cleaned up, and that might be better handled by adding `$values`, `$keys`, and `$pairs`, so I'll leave this open while I play around with a lazy iterator there.

**Comment by stevenhauser** [comment]
Thanks for the examples @jdeal, that definitely made it easier to understand. I think leaving `$each` as-is makes a lot of sense, too. Something like option 3 `$values` could definitely be a valuable pattern as well if a similar situation comes up.

**Comment by jdeal** [comment]
Closing this issue, but I wrote [another book](https://github.com/jdeal/qim/issues/5) if you want to check that out.
