### ISSUE TITLE
Question: is it possible to transform the already cloned object?

### ISSUE THREAD

**Issue by ngryman** [jdeal/qim#6]
Hey,

Sorry if it's already mentioned in the docs, but I don't understand how to achieve what I want.
I have normalized data in my store:
 - a list of `enemy`
 - a list of `spell`

Each enemy has 2 spells, so I'm trying to do a simple *join*:
```js
const selectSpells = (enemy, state) => (
  select([
    'spells',
    $each,
    $apply(({ key }) => (
      find(['data', 'spells', key], state)
    ))
  ], enemy)
)
```

Until this point everything work as expected, I've got enemies having their spells filled in instead of ids. Everything has been cloned to I'm not mutating the store.

Each `spell` has a predefined *cooldown* and each `enemy` has a `cdr` attribute. The `cdr` is simply a ratio that lowers the predefined cooldown. I would like to apply this transformation so each user has its `spells` with the adjusted `cooldown`.

Here is one of my attempts:
```js
select([
    'spells',
    $each,
    $apply(({ key }) => (
      find(['data', 'spells', key], state)
    )),
    $apply(spell => {
      spell.cooldown *= (1 - ennemy.cdr)
      return spell
    })
  ], enemy)
```

No matter what I try, my normalized data is mutated, so the initial predefined cooldown for each spells gets mutated.

So my question is, is it possible to `$apply` on the result object (already cloned) instead of the source one? I reckon that I'm probably missing something somewhere :)

Thanks for the help.

**Comment by jdeal** [comment]
Hey @ngryman, thanks for trying out qim! :-) Looks like you started composing things together which is cool, but you just have to go one step further:

```js
select([
  'spells',
  $each,
  $apply(({ key }) => (
    find(['data', 'spells', key], state)
  )),
  $apply(
    update(['cooldown', $apply(cooldown => cooldown * (1 - enemy.cdr))])
  )
], enemy)
```

I'm using a curried version of `update` there. Note there's no second parameter, so it just returns a function that takes data. I plug that into the `$apply` so it gets used to update the spell immutably.

**Comment by ngryman** [comment]
@jdeal Thanks! Now I see your solution I feel dumb :) I expected the whole input object to be clones somewhere in between the 2 `$apply`, but I guess that makes sense. Thanks for your time :)

Oh and all functions of `qim` are curryable? 👏

**Comment by jdeal** [comment]
@ngryman Ah, yeah, cloning only happens when an object is mutated (by qim). To allow for mutations like that, we'd have to deeply clone, which would be expensive and remove any ability to do equality comparisons on unchanged branches.

And yep, all functions listed in [the API section](https://github.com/jdeal/qim#api) are curried.

**Comment by ngryman** [comment]
@jdeal 👏 Oh then it would be awesome to highlight it more because I didn't get it while reading the docs.

Not necessary the right place to ask about that (if you have a better place tell me), I have 2 questions for you:

1. Do you plan to add memoization? I mainly use `qim` as a selector to compute derived data, and similar libraries (like `reselect`) offer this feature.

2. This library is really neat and navigators is a truly powerful tool, but they impose a kind of "painful" API why may turn some new users away (I know that's silly but...). The main pain-point would be `path` defined by arrays. It makes perfect sense but it's also sometimes painful to use, error prone, and make the code harder to read.

Would you consider also supporting var args so it becomes:

```js
select('path', 'to', $nav, 'property', state)
```

**Comment by jdeal** [comment]
Added a quick note to the readme about currying, for now.

@ngryman Do you mind adding those questions as two separate issues?
