### ISSUE TITLE
Feature: memoization

### ISSUE THREAD

**Issue by ngryman** [jdeal/qim#7]
Do you plan to add memoization? I mainly use qim as a selector to compute derived data, and similar libraries (like reselect) offer this feature.

rel #6

**Comment by jdeal** [comment]
At Zapier where we use it now, we use it inside reselect selectors, but we let reselect do the actual memoization. The conversation has popped up to maybe add memoization to qim, but I'd want to avoid bloating or over-complicating qim too much. In the short-term I'll hopefully be cleaning up and simplifying the internal source, specifically relating to [lazy/iterable](https://github.com/jdeal/qim/issues/5) support. That refactoring _may_ open up some doors to features like this, but I haven't yet thought much about how that would work.

**Comment by ngryman** [comment]
Alright seems legit, thanks again for you answer 👍
