### ISSUE TITLE
Feature request: add insert() or after() for inserting into arrays

### ISSUE THREAD

**Issue by IamCarbonMan** [jdeal/qim#9]
This one I would think is pretty simple and there's probably already an easy way to do it that I'm not seeing. But if there's no built in way I think there ought to be:

```
set([5], 5, [0, 1, 2, 3, 4]) // = [0, 1, 2, 3, 5] .... no, that's not it...

after([5], 5, [0, 1, 2, 3, 4]) // = [0, 1, 2, 3, 4, 5] -- that's what I want
```

**Comment by jdeal** [comment]
@IamCarbonMan Hmm, I just added a passing test which works the way you described in your "that's what I want" example:

https://github.com/jdeal/qim/commit/5b0bbc2c06e368e13176e057c36cd4b4a63d64e8

So I'm not quite sure what you're wanting. There's also an `$end` that lets you concatenate an array onto the end of an array:

https://github.com/jdeal/qim#end

which you could use like this:

```js
set([$end], [5], [0, 1, 2, 3, 4])
// [ 0, 1, 2, 3, 4, 5 ]
```

**Comment by IamCarbonMan** [comment]
How one would add an item into the middle of an array?

**Comment by jdeal** [comment]
You can use an empty slice for that.

```js
set([$slice(1,1)], ['b'], ['a', 'c']);
// ['a', 'b', 'c']
```

**Comment by sg-4xxi** [comment]
@jdeal could you add this case into the documentation?
